### ISSUE TITLE
game crashes when mod is used

### ISSUE THREAD

**Issue by Rahib777-7** [Minecraft-Malware-Prevention-Alliance/PipeBlocker#16] opened 2023-08-06 17:45 UTC
https://mclo.gs/Hyf16NE

**Comment by ThexXTURBOXx** [comment] 2023-08-07 21:51
That's pretty interesting: If you compare the JRE that the official Minecraft launcher ships, there is no `sun.misc.ObjectInputFilter`:
![grafik](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/assets/12763829/149f7358-d3b4-4f83-83f4-812ef297fcc8)

However, it is worth mentioning that it is nevertheless used in the code in many places such as the `ObjectInputStream` itself or `java.rmi.server.UnicastRemoteObject` (to list two)

**Comment by ThexXTURBOXx** [comment] 2023-08-07 21:53
Also, this is the same as #7 :)

**Comment by xyzeva** [comment] 2023-08-17 21:27
Duplicate of #7

**Closed by xyzeva** 2023-08-17 21:27 UTC
