### ISSUE TITLE
Can not join world even with patched EnderCore

### ISSUE THREAD

**Issue by AzureAqua** [Minecraft-Malware-Prevention-Alliance/PipeBlocker#5] opened 2023-07-29 23:35 UTC
As title suggests, with Pipeblocker and EnderCore 0.5.78 installed the OIS are still filtered.
[latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12208245/latest.log)

**Comment by Semisol** [comment] 2023-07-30 08:33
Does this work now?

**Comment by AzureAqua** [comment] 2023-07-30 12:18
Was there a new build published anywhere?

**Comment by xyzeva** [comment] 2023-07-30 12:30
> Was there a new build published anywhere?

No, the mod pulls the allowlist from our github pages URL

**Comment by AzureAqua** [comment] 2023-07-30 12:38
[latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12209219/latest.log)
Still seems to not be working

**Comment by Semisol** [comment] 2023-07-30 12:52
> [latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12209219/latest.log) Still seems to not be working

could you try this build?
[static.semisol.dev/pipeblocker-forge17_112-1.1.0.jar](https://static.semisol.dev/pipeblocker-forge17_112-1.1.0.jar)

**Comment by AzureAqua** [comment] 2023-07-30 13:10
[latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12209261/latest.log)
Still not working

**Comment by Semisol** [comment] 2023-07-30 13:13
Thank you, should work now

**Comment by AzureAqua** [comment] 2023-07-30 13:39
[latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12209319/latest.log)
Still seems to not be working, have tried both the build linked above and the Modrinth release

**Comment by xyzeva** [comment] 2023-07-30 14:34
> [latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12209319/latest.log) Still seems to not be working, have tried both the build linked above and the Modrinth release


how about now?

**Comment by Semisol** [comment] 2023-07-30 14:35
> > [latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12209319/latest.log) Still seems to not be working, have tried both the build linked above and the Modrinth release
> 
> how about now?

we have a bug in the check logic not accounting for ararys, will fix that

**Comment by Semisol** [comment] 2023-07-30 14:45
Okay, we published a new version: https://modrinth.com/mod/pipeblocker/version/kOV9y6wV

**Comment by AzureAqua** [comment] 2023-07-30 15:22
[latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12209567/latest.log)
Still no luck

**Comment by Semisol** [comment] 2023-07-30 18:32
> [latest.log](https://github.com/Minecraft-Malware-Prevention-Alliance/PipeBlocker/files/12209567/latest.log) Still no luck

Okay, can you follow the steps in #8?

**Comment by xyzeva** [comment] 2023-07-30 21:41
Tested - This is now fixed and #9 is a duplicate of this.

**Closed by xyzeva** 2023-07-30 21:41 UTC
